services:
  postgres:
    image: postgres:latest
    container_name: nestjs_recipes_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  postgres_data:

networks:
  nestjs_network:
    driver: bridge
